// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            Future<String>  verifierOpen() => RustLib.instance.api.crateApiVerifierVerifierOpen();

Future<String>  verifierSnapshot({required String epoch }) => RustLib.instance.api.crateApiVerifierVerifierSnapshot(epoch: epoch);

Future<String>  candidateImport({required String epoch , required String selectionToken }) => RustLib.instance.api.crateApiVerifierCandidateImport(epoch: epoch, selectionToken: selectionToken);

Future<String>  suiteStart({required String epoch , required String suiteId }) => RustLib.instance.api.crateApiVerifierSuiteStart(epoch: epoch, suiteId: suiteId);

Future<String>  operationNext({required String epoch , required String operationId , BigInt? ackSequence }) => RustLib.instance.api.crateApiVerifierOperationNext(epoch: epoch, operationId: operationId, ackSequence: ackSequence);

Future<String>  operationCancel({required String epoch , required String operationId }) => RustLib.instance.api.crateApiVerifierOperationCancel(epoch: epoch, operationId: operationId);

Future<String>  candidateRemove({required String epoch }) => RustLib.instance.api.crateApiVerifierCandidateRemove(epoch: epoch);

Future<String>  reportPrepare({required String epoch , required String operationId }) => RustLib.instance.api.crateApiVerifierReportPrepare(epoch: epoch, operationId: operationId);

            
            